### ISSUE TITLE
别的学校的校园网能用吗

### ISSUE THREAD

**Issue by Ding-YF** [tomtiao/GDUF-Auto-Login#2]

**Comment by tomtiao** [comment]
如果学校也是通过网页认证登录，手动修改content.js和manifest.json应该能用。

问题主要在不同学校登录请求可能不一样。首先得找到登录页面发送的登录请求，可以在浏览器的开发人员工具（F12）的网络选项卡里看看。

之前写扩展的时候没考虑过其他学校，部分代码耦合。有机会我试试更加通用的解法。

**Comment by Ding-YF** [comment]
不会java啊，哪只能等您更新更加普适的代码了

**Comment by Ding-YF** [comment]
我们也是通过网页登录的
